### PR TITLE
Added NonEditable property for future use by AdminUI

### PR DESCRIPTION
**Pull request by scottbrady91**

### CODE REVIEW

**Comment by scottbrady91** [comment]
Mappers TODO once IdentityServer4.Storage entities released: https://github.com/IdentityServer/IdentityServer4.Storage/pull/1

**Comment by VictorioBerra** [comment]
@scottbrady91 @leastprivilege 

Is the goal to be able to remove the `ExtendedClients/ApiResources/IdentityResources` requirement for AdminUI?  I am assuming this because I also saw this commit: https://github.com/IdentityServer/IdentityServer4.EntityFramework.Storage/commit/cdcbce572e671fe0f991b634e2a6f24032a3219e#diff-daf1cc00577e0e8df15c9adf6e0e1c68

**Comment by scottbrady91** [comment]
Potentially. However, AdminUI will still need some custom tables for things such as auditing.

**Comment by VictorioBerra** [comment]
I saw that the new fields like `Updated` and `LastAccessed` had no references and did not map to the corresponding Client. There was also no issue tagged to the commits for these schema changes which is why I ask. I was just wondering what prompted the need for schema changes.

**Pull request merged**
